---
title: "About Me"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: sandstone
    source_code: embed 
---
<p>&nbsp;</p>
<p>&nbsp;</p>
# **Academic Background**
<p>&nbsp;</p>
## [Mailman School of Public Health, Columbia University](https://www.publichealth.columbia.edu/)
### Master of Public Health in Sociomedical Sciences, May 2022
#### Certificate in Comparative Effectiveness Outcomes Research
* Scholar, Huo Family Foundation
* Research Assistant, Averting Maternal Death & Disability Program
* Staff Writer, Columbia Health Dispatch
* Mentor, R.I.S.E. (Resilience, Inclusion, Solidarity & Empowerment)
* Programs: R, SAS, STATA, SPSS, TreeAge
* Certifications: Human Subjects Protection SBR, CITI Certification; Protecting Human Research Participants Training Certificate, PHRP
* Public Health Fellow, Initiative to End Girls’ Incarceration, The Vera Institute of Justice
<p>&nbsp;</p>

## [Seattle Pacific University](https://spu.edu/)
### Bachelor of Arts in Political Science, June 2015
#### Concentration in International Affairs
* International Affairs Student of the Year
* Summa Cum Laude
* Dean’s List
<p>&nbsp;</p>

# **Professional Experience**
<p>&nbsp;</p>
## [Bill & Melinda Gates Foundation](https://www.gatesfoundation.org/)
#### Program Coordinator | K-12 Education, 2019 - 2020
#### Program Assistant | TB & HIV, 2018 - 2019
#### Program Assistant | Global Health Office of the President, 2016
<p>&nbsp;</p>
## [Fulbright Program, U.S. Department of State](https://www.macee.org.my/)
#### Grantee | Malaysia, 2017
[Guest Article published on Fulbright Malaysia ETA Blog](https://fulbrightmalaysiaeta.blogspot.com/2017/10/satu-malaysia-rocking-boats-and-eating.html)
<p>&nbsp;</p>
## [The Borgen Project](https://borgenproject.org/)
#### Donor Relations & Operations Manager, 2015 - 2016
<p>&nbsp;</p>

# **Community Engagement**
<p>&nbsp;</p>
## [The Bush School](https://bushblazersathletics.com/)
#### Assistant Middle School Girls Basketball Coach, 2019 - 2020
<p>&nbsp;</p>
## [Refugee Women's Alliance](https://www.rewa.org/)
#### Postsecondary Success Program Volunteer, 2018 - 2020
<p>&nbsp;</p>
## [SUKA Society](https://www.sukasociety.org/)
#### ESL Teacher, 2017
<p>&nbsp;</p>
## [The Language Institute](https://www.upc.org/connect/internationals/english-as-a-second-language/)
#### Intermediate ESL Teacher, 2015 - 2016
