---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed 
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

``` {r}
data("rest_inspec")

manhattan_rest = rest_inspec %>%
  janitor::clean_names() %>%
    filter(boro == "MANHATTAN") %>%
  select(cuisine_description, dba, critical_flag, inspection_date, inspection_type, score, violation_code, building, street, zipcode, grade) %>%
  drop_na(score) %>%
  drop_na(grade) 

all_rest = rest_inspec %>%
  janitor::clean_names() %>%
  filter(boro != "Missing") %>%
  select(boro, cuisine_description, dba, critical_flag, inspection_date, inspection_type, score, violation_code, building, street, zipcode, grade) %>%
  drop_na(score) %>%
  drop_na(grade) 
```

Column {data-width=650}
-----------------------------------------------------------------------

### Manhattan Restaurant Inspections by Type of Cuisine and Associated Scores and Grades. 

```{r}
manhattan_rest %>%
   mutate(
    text_label = str_c("Grade: ", grade)
  ) %>% 
  plot_ly(
    x = ~cuisine_description, y = ~score, type = "scatter", mode = "markers", color = ~grade, text = ~text_label, alpha = 0.5)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Number of Restaurant Inspections per Borough

```{r}
all_rest %>%
  count(boro) %>%
  mutate(boro = fct_reorder(boro, n)) %>% 
  drop_na(boro) %>%
  plot_ly(
    x = ~boro, y = ~n, color = ~boro, type = "bar", colors = "viridis")
```

### Average and Range of Inspection Scores among the Boroughs. 

```{r}
all_rest %>%
  mutate(
    boro = fct_reorder(boro, score)
    ) %>%
  plot_ly(
    y = ~score, color = ~boro, type = "box", colors = "viridis")
```

